### ISSUE TITLE
知识图谱可视化展示相关问题

### ISSUE THREAD

**Issue by yinchunlin** [ownthink/KG-View#2]
![1png](https://user-images.githubusercontent.com/56822811/67372003-d0a3fa00-f5af-11e9-8a58-8990919a7521.png)

运行“kgview.py ”时出现上图的问题，然后我直接在浏览器输入“https://api.ownthink.com/kg/knowledge?entity=“图灵””时，返回的数据为空（即"data": {}），如下图所示：
![2](https://user-images.githubusercontent.com/56822811/67372032-d994cb80-f5af-11e9-877d-a529e7b5e7dc.png)
这是因为你们的后台数据出了问题，调用不到数据的原因吗？

**Comment by ownthink** [comment]
这是你图灵给人家加上双引号了，数据问题，我晚上回去看下。。


郑文裕


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"yinchunlin"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月23日(星期三) 下午4:12
收件人:&nbsp;"ownthink/KG-View"<KG-View@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[ownthink/KG-View] 知识图谱可视化展示相关问题 (#2)





 
运行“kgview.py ”时出现上图的问题，然后我直接在浏览器输入“https://api.ownthink.com/kg/knowledge?entity=“图灵””时，返回的数据为空（即"data": {}），如下图所示：
 
 这是因为你们的后台数据出了问题，调用不到数据的原因吗？

**Comment by yinchunlin** [comment]
> 这是你图灵给人家加上双引号了，数据问题，我晚上回去看下。。 郑文裕 &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"yinchunlin"<notifications@github.com&gt;; 发送时间:&nbsp;2019年10月23日(星期三) 下午4:12 收件人:&nbsp;"ownthink/KG-View"<KG-View@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;[ownthink/KG-View] 知识图谱可视化展示相关问题 (#2) 运行“kgview.py ”时出现上图的问题，然后我直接在浏览器输入“[https://api.ownthink.com/kg/knowledge?entity=“图灵””时，返回的数据为空（即"data](https://api.ownthink.com/kg/knowledge?entity=%E2%80%9C%E5%9B%BE%E7%81%B5%E2%80%9D%E2%80%9D%E6%97%B6%EF%BC%8C%E8%BF%94%E5%9B%9E%E7%9A%84%E6%95%B0%E6%8D%AE%E4%B8%BA%E7%A9%BA%EF%BC%88%E5%8D%B3%22data)": {}），如下图所示： 这是因为你们的后台数据出了问题，调用不到数据的原因吗？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
